from pathlib import Path


def read_lines(path: Path) -> list[str]:
    with open(path, "r", encoding="utf-8") as f:
        return [line.strip() for line in f]


def rewrite_abaqus_lines(lines: list[str]) -> list[str]:
    header = []
    body = []
    in_header = False

    for stripped in lines:
        if stripped.startswith("*HEADING"):
            in_header = True
            header.append(stripped)
            continue

        if stripped.startswith("*") and in_header:
            in_header = False
            body.append("*PART, NAME=PART")

        if in_header:
            header.append(stripped)
            continue

        if stripped == "*ELEMENT, TYPE=C3D4":
            stripped = "*ELEMENT, TYPE=C3D4, ELSET=TETRA"

        body.append(stripped)

    if not header:
        return body

    return [
        header[0],
        "Generated by mesh-to-inp",
        "**",
        "** Converted mesh with duplicated interface nodes and cohesive elements",
        *body,
    ]


def find_next_element_id(lines: list[str]) -> int:
    for line in reversed(lines):
        if line and not line.startswith("*"):
            return int(line.split(",")[0]) + 1

    raise ValueError("Could not find any element definition line.")


def make_material_lines(materials) -> list[str]:
    lines: list[str] = []

    if not materials:
        return lines

    lines.extend(make_comment("MATERIAL DEFINITIONS"))

    for material in materials:
        lines.extend(make_subcomment(material.name))

        lines.extend(
            [
                f"*MATERIAL, NAME={material.name}",
                "*DENSITY",
                f"{format_float(material.density)}",
                "*ELASTIC",
                (
                    f"{format_float(material.elastic.E)}, "
                    f"{format_float(material.elastic.nu)}"
                ),
                "*PLASTIC",
                f"{format_float(material.plastic.yield_stress)}, 0.",
            ]
        )

    return lines


def make_solid_section_lines(section) -> list[str]:
    return [
        *make_comment("SECTION DEFINITIONS"),
        "*SOLID SECTION, "
        f"ELSET={section.elset}, "
        f"MATERIAL={section.material}",
    ]

def make_assembly_lines(
    part_name: str = "PART",
    instance_name: str = "PART-1",
) -> list[str]:
    return [
        *make_comment("ASSEMBLY"),
        "*ASSEMBLY, NAME=Assembly",
        f"*INSTANCE, NAME={instance_name}, PART={part_name}",
        "*END INSTANCE",
        "*END ASSEMBLY",
    ]


def make_comment(title: str) -> list[str]:
    line = "** " + "=" * 76
    return [
        "",
        line,
        f"** {title}",
        line,
    ]


def make_subcomment(title: str) -> list[str]:
    return [
        "",
        f"** --- {title} ---",
    ]


def format_float(value: float) -> str:
    return f"{value:.12g}"