from pathlib import Path


def read_lines(path: Path) -> list[str]:
    with open(path, "r", encoding="utf-8") as f:
        return [line.strip() for line in f]


def rewrite_abaqus_lines(lines: list[str]) -> list[str]:
    header = []
    body = []
    in_header = False

    for stripped in lines:
        if stripped.startswith("*HEADING"):
            in_header = True
            header.append(stripped)
            continue

        if stripped.startswith("*") and in_header:
            in_header = False
            body.append("*PART, NAME=PART")

        if in_header:
            header.append(stripped)
            continue

        if stripped == "*ELEMENT, TYPE=C3D4":
            stripped = "*ELEMENT, TYPE=C3D4, ELSET=TETRA"

        body.append(stripped)

    if not header:
        return body

    return [
        header[0],
        "Generated by mesh-to-inp",
        "**",
        "** Converted mesh with duplicated interface nodes and cohesive elements",
        *body,
    ]


def find_next_element_id(lines: list[str]) -> int:
    for line in reversed(lines):
        if line and not line.startswith("*"):
            return int(line.split(",")[0]) + 1

    raise ValueError("Could not find any element definition line.")


def make_material_lines(materials) -> list[str]:
    lines: list[str] = []

    if not materials:
        return lines

    lines.extend(make_comment("MATERIAL DEFINITIONS"))

    for material in materials:
        lines.extend(make_subcomment(material.name))

        lines.extend(
            [
                f"*MATERIAL, NAME={material.name}",
                "*DENSITY",
                f"{format_float(material.density)}",
                "*ELASTIC",
                (
                    f"{format_float(material.elastic.E)}, "
                    f"{format_float(material.elastic.nu)}"
                ),
                "*PLASTIC",
                f"{format_float(material.plastic.yield_stress)}, 0.",
            ]
        )

    return lines


def make_solid_section_lines(section) -> list[str]:
    return [
        *make_comment("SECTION DEFINITIONS"),
        "*SOLID SECTION, "
        f"ELSET={section.elset}, "
        f"MATERIAL={section.material}",
    ]

def make_assembly_lines(
    part_name: str = "PART",
    instance_name: str = "PART-1",
) -> list[str]:
    return [
        *make_comment("ASSEMBLY"),
        "*ASSEMBLY, NAME=Assembly",
        f"*INSTANCE, NAME={instance_name}, PART={part_name}",
        "*END INSTANCE",
        "*END ASSEMBLY",
    ]


def make_quasi_static_step_with_cloads_lines(
    nodal_forces,
    step,
    rigid_body_constraints=None,
    instance_name: str = "PART-1",
    force_tolerance: float = 1.0e-12,
) -> list[str]:
    nlgeom = "YES" if step.nlgeom else "NO"
    inc = step.increments

    lines: list[str] = [
        *make_comment("STEP"),
        f"*STEP, NAME={step.name}, NLGEOM={nlgeom}, INC={inc.max_number}",
        "*STATIC",
        (
            f"{format_float(inc.initial)}, "
            f"{format_float(inc.total)}, "
            f"{format_float(inc.minimum)}, "
            f"{format_float(inc.maximum)}"
        ),
    ]

    lines.extend(make_time_incrementation_controls_lines(step.controls))

    lines.extend(
        make_rigid_body_constraint_lines(
            rigid_body_constraints,
            instance_name=instance_name,
        )
    )

    lines.extend(
        [
            "",
            "** --- Macroscopic stress loading as nodal concentrated forces ---",
            "*CLOAD",
        ]
    )

    for node_id in sorted(nodal_forces.forces):
        force = nodal_forces.forces[node_id]

        for dof, value in enumerate(force, start=1):
            if abs(value) <= force_tolerance:
                continue

            lines.append(
                f"{instance_name}.{node_id}, {dof}, {format_float(float(value))}"
            )

    lines.extend(["", "*END STEP"])

    return lines


def make_time_incrementation_controls_lines(controls) -> list[str]:
    if controls is None:
        return []

    time_controls = controls.time_incrementation

    if time_controls is None:
        return []

    if not time_controls.enabled:
        return []

    line_1 = [
        time_controls.max_equilibrium_iterations,
        time_controls.cutback_after_equilibrium_iterations,
        time_controls.max_attempts_per_increment,
        time_controls.max_severe_discontinuity_iterations,
        time_controls.severe_discontinuity_iterations_for_increase,
    ]

    line_2 = [
        time_controls.cutback_factor_after_divergence,
        time_controls.cutback_factor_slow_convergence,
        time_controls.cutback_factor_too_many_iterations,
        time_controls.increase_factor_after_easy_increments,
        time_controls.max_increment_increase_factor,
    ]

    lines = [
        "",
        "** --- Time incrementation controls ---",
        "*CONTROLS, PARAMETERS=TIME INCREMENTATION",
    ]

    if any(value is not None for value in line_1):
        lines.append(_format_optional_abaqus_values(line_1))

    if any(value is not None for value in line_2):
        if not any(value is not None for value in line_1):
            lines.append("")
        lines.append(_format_optional_abaqus_values(line_2))

    return lines


def _format_optional_abaqus_values(values: list[object | None]) -> str:
    formatted: list[str] = []

    for value in values:
        if value is None:
            formatted.append("")
        elif isinstance(value, float):
            formatted.append(format_float(value))
        else:
            formatted.append(str(value))

    while formatted and formatted[-1] == "":
        formatted.pop()

    return ", ".join(formatted)


def make_rigid_body_constraint_lines(
    constraints,
    instance_name: str = "PART-1",
) -> list[str]:
    if not constraints:
        return []

    lines = [
        "",
        "** --- Minimal rigid body constraints ---",
        "*BOUNDARY",
    ]

    for constraint in constraints:
        lines.append(
            f"{instance_name}.{constraint.node_id}, "
            f"{constraint.first_dof}, "
            f"{constraint.last_dof}, "
            f"{format_float(constraint.value)}"
        )

    return lines


def make_comment(title: str) -> list[str]:
    line = "** " + "=" * 76
    return [
        "",
        line,
        f"** {title}",
        line,
    ]


def make_subcomment(title: str) -> list[str]:
    return [
        "",
        f"** --- {title} ---",
    ]


def format_float(value: float) -> str:
    return f"{value:.12g}"